name: OspreyRidge
favicon: null
layout_spectrum: 0.7163515752181411
typography_spectrum: 0.746183603303507
title: OspreyRidge
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#473819'
    - '#b3a622'
    - '#787013'
    - '#f2db31'
  brandStrength: 0.9649365083314478
  lightness: 0.47083163959905505
  saturation: 0.6578409501817077
  rhythmicContrast: 0.7852165130898356
purpose: []
